development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: library_development
  username: root
  password: mu113n
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: library_test
  username: root
  password: mu113n
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: library_production
  username: root
  password: mu113n
  host: onosen.com
